### ISSUE TITLE
Calendar App

### ISSUE THREAD

**Issue by Ibinola** [chingu-voyages/v36-toucans-team-05#14]
**__User Story__**

As a user, I want to be able to view  
- [x] The landing page.
- [x] The months, dates, and days of the week.
- [x] A button/arrows on the calendar to change between years.
- [x] Add an event when a date is clicked.

**Comment by shijiezhou1** [comment]
Some extra from my opinion

- [x] Tasks - Create, manage and view your task note on the calendar date that clicked
- [x] Schedule simple events
- [x] Customize the theme of the calendar
- [x] Allow adding public holidays of many countries around the world (optional)
- [x] Share and view calendar (optional)
- [x] Support many different languages
- [x] Alias timezone conversion
